const origin = 'https://vsexperience.com.br';
const pages = [
  { path: '/', file: 'index.html', key: 'home', title: 'Criação de sites e UX/UI | Victor Santos · VS Experience', description: 'Estratégia, UX/UI e desenvolvimento de sites e produtos digitais. Conheça os projetos da VS Experience e a consultoria de Victor Santos.', heading: 'Design e tecnologia\npara o seu negócio.', sub: 'Estratégia · UX/UI · Desenvolvimento', label: 'Victor Santos · VS Experience' },
  { path: '/en/', file: 'en/index.html', key: 'home-en', title: 'Website development & UX/UI | Victor Santos · VS Experience', description: 'Strategy, UX/UI and website development with VS Experience. Explore digital projects, design systems and consulting with Victor Santos.', heading: 'Design and technology\nfor your business.', sub: 'Strategy · UX/UI · Development', label: 'Victor Santos · VS Experience', lang: 'en' },
  { path: '/servicos/', file: 'servicos/index.html', key: 'servicos', title: 'Criação de sites e sistemas: serviços | VS Experience', description: 'Landing pages, sites institucionais, lojas virtuais, sistemas e design systems. Veja o processo, os prazos e as faixas de investimento da VS Experience.', heading: 'Seu próximo projeto\ncomeça aqui.', sub: 'Sites · E-commerce · Sistemas · Design systems', label: 'Serviços de criação' },
  { path: '/servicos/landing-page/', file: 'servicos/landing-page/index.html', key: 'landing-page', title: 'Criação de landing page: preço e prazo | VS Experience', description: 'Criação de landing page com copy, design e desenvolvimento. Conheça o processo, o prazo de 10 a 15 dias úteis e as faixas de investimento da VS Experience.', heading: 'Uma oferta clara.\nUm próximo passo.', sub: 'Copy · Design · Desenvolvimento', label: 'Criação de landing page' },
  { path: '/servicos/site-institucional/', file: 'servicos/site-institucional/index.html', key: 'site-institucional', title: 'Criação de site institucional | VS Experience', description: 'Criação de site institucional para apresentar sua empresa e gerar oportunidades. Veja o processo, os prazos e as faixas de investimento da VS Experience.', heading: 'Sua empresa,\nbem apresentada.', sub: 'Estratégia · Design · Desenvolvimento', label: 'Criação de site institucional' },
  { path: '/servicos/e-commerce/', file: 'servicos/e-commerce/index.html', key: 'e-commerce', title: 'Criação de loja virtual e e-commerce | VS Experience', description: 'Criação de loja virtual com design, desenvolvimento e integrações definidas no escopo. Conheça o processo e as faixas de investimento da VS Experience.', heading: 'Uma loja pensada\npara a compra.', sub: 'Experiência · Design · Integrações', label: 'Criação de e-commerce' },
  { path: '/servicos/sistemas-saas/', file: 'servicos/sistemas-saas/index.html', key: 'sistemas-saas', title: 'Desenvolvimento de sistemas web e SaaS | VS Experience', description: 'Design e desenvolvimento de sistemas web e SaaS, do escopo às interfaces e integrações. Veja o processo e as faixas de investimento da VS Experience.', heading: 'Do fluxo de trabalho\nao produto digital.', sub: 'UX/UI · Desenvolvimento · Integrações', label: 'Sistemas web e SaaS' },
  { path: '/servicos/design-system/', file: 'servicos/design-system/index.html', key: 'design-system', title: 'Criação de design system: Figma e código | VS Experience', description: 'Design system com tokens, componentes e documentação para interfaces consistentes. Conheça as entregas em Figma e código e as faixas de investimento.', heading: 'Consistência para\no produto crescer.', sub: 'Tokens · Componentes · Documentação', label: 'Criação de design system' },
  { path: '/bio.html', file: 'bio.html', key: 'bio', title: 'Victor Santos: projetos e contato | VS Experience', description: 'Conheça Victor Santos, Product Designer e Design Engineer. Acesse projetos, redes sociais e contato para consultoria, UX/UI e desenvolvimento de sites.', heading: 'Victor Santos.', sub: 'Product Designer & Design Engineer', label: 'Projetos e contato' }
];
for (const p of pages) { p.url = origin + p.path; p.image = origin + '/assets/images/og/' + p.key + '-vs.jpg'; p.alt = p.label + ' — ' + p.heading.replace(/\n/g, ' '); }
module.exports = { origin, pages };
